name: Generate Coverage Badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      # Run tests and collect coverage profile
      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out

      # Extract total coverage and generate badge
      - name: Generate coverage badge
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          COLOR="red"
          if (( $(echo "$COVERAGE > 90" | bc -l) )); then
            COLOR="brightgreen"
          elif (( $(echo "$COVERAGE > 80" | bc -l) )); then
            COLOR="green"
          elif (( $(echo "$COVERAGE > 70" | bc -l) )); then
            COLOR="yellow"
          elif (( $(echo "$COVERAGE > 60" | bc -l) )); then
            COLOR="orange"
          fi

          cat > coverage.svg <<EOF
          <svg xmlns="http://www.w3.org/2000/svg" width="120" height="20">
            <linearGradient id="b" x2="0" y2="100%">
              <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
              <stop offset="1" stop-opacity=".1"/>
            </linearGradient>
            <mask id="a">
              <rect width="120" height="20" rx="3" fill="#fff"/>
            </mask>
            <g mask="url(#a)">
              <rect width="65" height="20" fill="#555"/>
              <rect x="65" width="55" height="20" fill="#${COLOR}"/>
              <rect width="120" height="20" fill="url(#b)"/>
            </g>
            <g fill="#fff" text-anchor="middle"
              font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
              <text x="33" y="15" fill="#010101" fill-opacity=".3">coverage</text>
              <text x="33" y="14">coverage</text>
              <text x="92" y="15" fill="#010101" fill-opacity=".3">${COVERAGE}%</text>
              <text x="92" y="14">${COVERAGE}%</text>
            </g>
          </svg>
          EOF

          # Add or update the badge in README.md
          if grep -q '!\[coverage\]' README.md; then
            echo "✅ coverage.svg updated (${COVERAGE}%)"
          else
            echo "![coverage](./coverage.svg)" >> README.md
            echo "✅ added badge to README.md"
          fi

      # Commit and push the badge if it changed
      - name: Commit and push badge
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add coverage.svg README.md || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update coverage badge (${COVERAGE}%)"
            git push
          else
            echo "No changes to commit."
          fi
